### ISSUE TITLE
Any solution for the 429 error

### ISSUE THREAD

**Issue by brackhap** [ptrstn/deepl-translate#18]
I'm trying to use this package but I always get the 429 error. Is there any solution?
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\deepl.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\deepl\__main__.py", line 52, in main
    print(deepl.translate(source_language, target_language, text, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\deepl\api.py", line 56, in translate
    response.raise_for_status()
  File "C:\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://www2.deepl.com/jsonrpc`

**Comment by pkeorley** [comment]
the same

**Comment by ptrstn** [comment]
Hello,

Unfortunately I am very busy at the moment, so I can't promise when I can investigate this problem.

Ill get back to you when I am able to figure out the issue.
